import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import { Container, Typography, Box, Button } from "@mui/material";
import ChevronRightIcon from '@mui/icons-material/ChevronRight';
import PetCard from "@/components/PetCard";
import Grid from '@mui/material/Grid';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {

  const pets = [1, 2, 3, 4, 5, 6, 7, 8];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <Container maxWidth='xl' sx={{ color: 'black', py: '40px', border: 1 }}>
          <Container sx={{border:1}}>
            <Container disableGutters >
              <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: '30px', px: '20px', }}>
                <Box>
                  <Typography variant="caption" sx={{ display: 'block', fontWeight: 500, fontSize: '16px' }}>
                    Whats new?
                  </Typography>
                  <Typography variant="h3" sx={{ display: 'block', color: 'primary.main' }}>
                    Take a look at some of our pets
                  </Typography>
                </Box>
                <Box sx={{ alignSelf: 'end' }}>
                  <Button variant="outlined" endIcon={<ChevronRightIcon />}>View more </Button>
                </Box>
              </Box>
            </Container>
            <Container >
              <Box>
                <Grid container spacing={2} >
                  {pets.map((pet) => (
                    <Grid size={{ xl: 3, md: 4, sm: 6 }}
                      key={pet}
                    >
                      <PetCard />
                    </Grid>
                  ))}
                </Grid>
              </Box>
            </Container>
          </Container>
          <Container sx={{mt:'50px', border:1, borderRadius:'20px', minHeight:'378px', backgroundImage:"url('/assets/Banner.png')", backgroundPosition:'cover'}}>
           
          </Container>
        </Container>
      </div>
    </>
  );
}
