import { useEffect } from "react";
import Script from "next/script";

export default function PZRobotWidget() {
  useEffect(() => {
    const storedAgentType = sessionStorage.getItem("agentType");
    let agentType = storedAgentType || "agent1";

    const select = document.getElementById("agentImg");
    if (select && storedAgentType) {
      select.value = storedAgentType;
    }

    const privateKey = `-----BEGIN PRIVATE KEY-----
LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRUUlCQURBTkJna3Foa2lH
OXcwQkFRRUZBQVNDQ1Nzd2dna25BZ0VBQW9JQ0FRREc5V29iaDBycHd5MXEKSkVu
ZlluNE5sbkk2RnFkL3ZpYWUxRlA5b3d4WmdEMUtxQXF5MXFzbGpTa29rdG02MXNx
ZWU3NHNSUjA1bUFseApHZ2Ywa2o4OU55UW9FTENVYTgzT3lGY0xTc1RCcDNWZ3Y0
MW9zQnB2Z1VoTW1pcFI4M0xncHlCUUE2RFlSTFFyClgva3FDWGt2UFFRQWc2NmpE
aVFRTWp2QTJXNXpWV3NaTlBNOEZCa3orU1NJd2ZPcjdvOHVnZjBpbUhLT2VxUWEK
SEtVZkxjSmdNLytDWW9wRXF0VU1wNTJJUUJWNmFvS1dJU1BSa2o4WU5IN2YwdXZO
UHk1T0dEQmtQZys3S0dwTApvRUJNcXdPTmtaSERuYjJxaTJwLysvWUozQUhkSlJq
a2JHSWVjNEtOZG5KTHNSUEhENUt6OEU3bUFTWXFnQjhqCjFGVTdGcHdQUm5wS3V0
eVArdVVWbENOWFIwVU9CRGtHSkNwdVIzdm9FU2RGVGxaWG1pbHFEbGJ3ZWR1UnEr
Y0kKWmU4WUtxY05jOHNnc1BHZlZIcVgwbzRkRE9tS1hhWjFCN3IwZ1NJd095Q3Fj
ZzhzV0F1TENZZnM4aDFmU3pOWgplbkphVHB5NGtHR3AwRGp2V1RwekdWQm5BU2E0
dER0Yk5Ia09kRWFjS1hBa2dkeWZjRktacjdaRWd4VlJFZGNvClR1Z0dqSzBFOHg3
ek9wVGVKVEltbHlhUWpWUHhOMUMxQWY2SWphY2s3WHlCZDNiQjl6RysvczNTTk9D
bWtnYWIKSkgrUUsxZWpKdW9hMW1TRU9PZFc1eHZYL09JSnQ4RC9SZjRqOUxWeWxJ
RVdpVkRWazN6bEh4S1RmaFNtZC9CKwo3SWRaMEhWdHloSzNzMHpLUkVhM0ZHUDl1
ejlxalFJREFRQUJBb0lDQUFab20wMWRzMFVLVzJraTJCcFE4dHgvCkx4aTk2QkZP
VDdJb0JyaVJ5dkVMRjI1VE1WMEhXeVh2Z1Jia2ZBenZwRUVzblRpUjFWb29rbzFK
R0Y2QlkzWVcKVTV6U3hNMVRGNk1FZ3dGREhFbGNtb1JPUjBETEExNzZIQmtUa2k5
bmx4aXphWEFLWGVENWZaQTBIRE9GY0pqYgo3MGdROWN3Y3hYNmNENTZyb2tvbXd6
ZGhwRUFZS2FPcDc4cFQ3UVJwdjhUd3ZQV2pVWFZUYi92RFZuSkZxQkF2ClBKaTNr
ZHFhWWhoeFFickV6YXhPeC93TC96cGQ2cGhlQUlRM0tBOUpiTFZwUkEzR2pmMHFW
Um93aEVHejlINVgKNVFrWENLZjRxNnFKdENnbkpRdzVpSzY2NndJdUdGTjBNRVJO
NU9ReGxUa2trWFlKTFhDTEJmWENmaWhVRnh5OApTeHVUeDloWTZvRUNwRSszU0xh
VGRCdUNBWFdiRzBhajFpaVZKYXZPTXJ0Y1plWUs1SlFlRW5RWXpNbGptOG5SCnZB
MXNLNXBnTGZINGowbTZyK2ZPeXpOTGd3WW5ueVJhdEpUZnZHZUZtdGJsa2NHYXVE
ak51djF6U3J4WDFhc0MKSm9vejQxMWdMSUxGVGwwWnBPUTljMDBiMVF5Y2hXdG5n
Sk1IUGFDVG9UN2ZJZFBZTGkyUU1vNTgrcDBaMDJlbgpTWVFMMWNBZnVPWWpLU0pi
SVhxSGd1Nm8zclIxRWpqeTFzOGl0RXUvSURLb1lUV2Z3L2RiZHhaNGJ6L1E4WHRi
CmZqMldVRUU3SVE1ZUN3d2k3LzhuZmV0Q2RNektFa3FBSzBncDNzaURJZVlRZnhj
VW93QU91KzJKaEtGK29pakUKU0dCZ2prQ0dTeU90Um90WXFlY2hBb0lCQVFEc3lm
YU9pSUYyRGxOUTlZS2w4MFBQOG4vWi9RWVBrVFl3bUxGSgprTWtUTk5SV3hlUlEy
TDhVdVpOTmRVMTB4MUZvY1hyckRjZTAveXc2emFURlpKOXdSWTlNWms0bTZ3Tjdq
aFlqClZqNlU1eTF6aTB6SG10NzVGWjZ4dFdKdzVLZTZuYWhLeEZqMHRjY2RJeHdh
QndRelcwTDBHRXFFb3lSOHpYaEQKckc0VFRmSU9hZVRXTjhlN1VlUngxQU5La1RU
b2V2NExxcnl2TEpzZE5UTEdaWkxUcDdFWEhaNVd0L2w4aXpYZgpWanVMS2JXSWpX
bzJvdEFGVTJGMGJhcHNHM1FSNUVTNGtXTytoUndYTHFmcW5DQk1WSDhYdnpLQzdo
Nmp5OGJiCnlMeVFjSVNsbmpxM3o2UkxCMjl4eDVSdXdWRFk3WWhmekVDVDhUbVNH
RnhqbUJsWkFvSUJBUURYR2JwTHI1bUYKMDd4c2ZqQmI1cm5RQmlLWHJDNU40WUpU
YkhOY0xTQnVKcmo5b1FCc0huaUhsZmlrYjFiNHJBV1hicHV1UFVYaQpKRFdSRFBT
MGRxdE1Gc3A3SS9DY3dhcmpITUdmc2xsVHhkWDArNkpwbDB2UkhFQ2hxck5tb1lk
V1hidWVQekptCnR3RmhpcjM4bHUxV1hZcDRvTDNzdVcwaUpmR0NvRVNkTVBxSVdu
R2ZSOHkzNHE1RjlzYnZHVlJEUUxnRldBR0MKZ25ndjczd1A5Smc4YnlZanRiUUl4
UGNxb3JjNEpvaXN5OHJSR1R4VzBXaUJmVVNvOHZGOG56bURxMXdOV2VtZQpINWV4
VVBpSUlZVVNDZzlhdnB3MUlsVDUxRy9xeDNtc2lJaHlDYzFZL3ZPbndobWNyeWZT
Q29lYkJzbVcyZ1pvCnRGT2U0MkpnMXdCVkFvSUJBQU1SUnJsbitVMWZPQ01YV3g3
dFBOYW56SkkxWGV1N3ROa0NVV0dqbDRkQkt2TUkKMDBGYzNYVFdScHM5UnNpWmdH
dDY5TjJ3cXdLa1A1MXZacEFNRXFpd3JmK09YN3JQVnBjMkt3RkFMOFZjRFZHdQoz
MHJDcmRyS05la1ZjWFlHOEVsUm00bUVhNmFYNkVGdllBRFNVSEtkM3dzc2VXS29m
bU9EZ2VoV2hvS0hndmcrCjFQRVZmZWZtVXJCS3o5UWFkM1gvaWVUNnpFRDBzZm01
NDdPQVExdXNrM1c2TTMvcUdEaE4wVi9ZVFNNcllpZW4KdFZXSjNHb0ZQNER6bnI2
UnlIb20yK0VNT1IrUnQrQnhBVW5meGVkWFBPSkEzdFdsWWc0N0tKTldVV01Kb2g1
SApJM21ZSGdlK3krbk1iUmJXT0VibkpOb2cya0ZRWWErTDB6NlRETmtDZ2dFQUtV
b0MvS3hFWisvdzUxS0JyZUpvCklJcE04WmhYZXhPaWxLam9xL1R0bUxkT0kwRllk
MmlSOGxUVFdaMFZzTDQwaEpEeXlVdHhzcXNJclVNelpjQ3gKdVBWWEFMUXhaNlcx
UzhzbFQ2WkloMUFlZGR3bm5PVXg1SDNyMmh5T08xRWVUWEhJcGVPenBRdlQ5QWxS
MXI2Ugo2RllrVW10b2ladytXcU8xN0VFZmFwMFFPa1JDTXpUeEV3c3NNTG5pRGR0
cTFVNERCT09UeHAyTXZJYlg1YWdwCjRNL2xIazJ1dFZBNXNiRnlRaEVEZzBmTE1z
QUpXUkR4WW9uTk9ERUtNY1hPb0h1d084L2FqRU84Tm9rNGE4a2oKWmdjUVUzYnJQ
VGZOMy9iclZNSGRsVVRRRERQZGV3dlZjWXBNcUVybTllYVhpU2FRWTZpT09tTUMr
aWpqcFhzZgowUUtDQVFBMEpGMktRaU5NSVFTTlBGZHZtK3NUR2pyZ3JCU0hQZFRM
TWd1L3dQdWQ2OXFENmlNWnEzYVNiMEYrClJsVGJxSURueGZsZlBjL1FUenJGbWxZ
RldKZW5hTDY3bUMrVFNjTE5VK3pDQTNhL2FWejdraUt6dU1ydzRJSUYKVllTWFZx
VzhubjIzem9YdU1CU1cwTXQvbW5qVFNUUDFoa0FyaCtMUVlmN0ZraXRzbkJyeFhp
VXVKck9IVTdSaAowVjJMdXdDbk5Ga0R0SjJVOVp6eXlLZFRvaHM0SHEvYzNJaER5
SW56aG5sMndOTS9XSDlabDFrdGxqdklVZVc0CjNiaVltMXFzUk01anlzYjFqdlVs
TDhHZTFNajNWa0ZKM2JMLzZZemliajFOdTI1b2lYQ0JUZllXLzJsMk4yRG0KUUV4
TWNUWEJxa1F1LzZIcC95elBHTno2TVdGUgotLS0tLUVORCBQUklWQVRFIEtFWS0t
LS0tCg==
-----END PRIVATE KEY-----`;

    const options = {
      client_id: "1",
      username: "username",
      privateKey,
      validate: async function (result) {
        return !!result.access_token;
      },
      onclose: function () {
        console.log("Widget closed");
      },
    };

    // initialize bot only after external script loads
    const interval = setInterval(() => {
      if (window.PZRobot) {
        const bot = new window.PZRobot(options);
        bot.open();
        clearInterval(interval);
      }
    }, 100);

    return () => clearInterval(interval);
  }, []);

  return (
    <>
      <Script
        src="https://pz-script.vercel.app/agent/agent_script/pz-robot.js"
        strategy="afterInteractive"
      />

      {/* Optional Agent Selector */}

    </>
  );
}
