import { useEffect } from "react";
import Script from "next/script";

export default function PZRobotWidget() {
  useEffect(() => {
    const storedAgentType = sessionStorage.getItem("agentType");
    let agentType = storedAgentType || "agent1";

    const select = document.getElementById("agentImg");
    if (select && storedAgentType) {
      select.value = storedAgentType;
    }

    const privateKey = `-----BEGIN PRIVATE KEY-----
LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRUUlCQURBTkJna3Foa2lH
OXcwQkFRRUZBQVNDQ1Nzd2dna25BZ0VBQW9JQ0FRQ1RqU2RFSjBMYzJadGQKYVQz
clJYMGpoWkpQcW1aczk3QW5ObVA3WlJFTFB2b1J4b2ZNTEZ0U1FLTlJXYi9PenB4
MGZYdmxSeG5ZYTRGcQpOcUR2SGNlUnMwbmNHT2ZpVi9NaVd6WVV3M1BIemxCakNz
V3hBYlhRNHVrL1JFQ2dLREpUazdjRkxWdDlNcHBzCkxnSnFmOHV0V21RTFpHK1V6
WDc1L04zOUwrVWxqTmtjNkU1VG5jMnpMdmVITURienlPUGIwVkk2TXZ3QkZmd2UK
anM5ajU2MHRqRHVQT1VVQTM2bytXcjVJYUV3bkFwOTE5M1Y1dTVDeS9LM05sZW1Q
TG1PZjRYbFMxUzJuRWNGbwpnVUcwZHd3cTIwSzV6VXJiMWZNOGFHdkpsdFRYTjBO
bHRlNkFJOWQ0WTNuWThQUjVWREZmcVpCQTRKRXdxdmV5CkZ0NktBc20wbXNyZ2tL
MGdJbUpWVzRsWXBleW9xUGREQ3BSWnJHVUZqdi9YWHA5eVJqbWJYNHlUcVJ0TjRh
bncKdzZiUStFclVDallOaitWenRnY2lkRmFIU3ovUC9BU2dqREM0a1hkckdUWXF6
Rmt6MjVZYmVJdENoaDlpdEdUSgpqTmVNZTZUYVphZVZsNFF2eWhjTjRLdXBPUEV2
enZHMWppTnRLYkJ4NGZaUnN4Ly9qWjhMM3hEN0xOYTRvQ29RClg3eHV2akVGSlRP
RndhS3pvejFiY3VoZ0JHdnkzN2xud3dzVWJ0a3J0a21yLzB3MjNHYVR1dk5KblFS
RUtHOEUKQitvb2QrSlRyR1QxaDk3TmZVa1k2ODF0dGdvZ1NtdkFTYmNhd0p3bFQv
cllaUG1yOG5XeDltUkhzYXFVQUhVZQpiQmVzS0pZaThVTmF6aEMyTXE0Tk1iWjgv
SG5nWVFJREFRQUJBb0lDQUJoZUZOQ0VFck9VdW1iMFZQWDdBck53ClFUS241Njl5
UGs5VGc3S0dSVE42d2VOWDlVcjA2UVg0blNBaVlYTmV4V2JWa2JXbjNDNy9jM1Fl
TTg0WmpjRCsKLzNaNlR5ZjBYTGV5b1lmNStWcCtOT0lPYXQ4L0hZN2RrbnRRemNM
RlcxT3R6dWxyZUFoV2t1WEZEc0FXSjlzUwpxazFaVjdZVzNvbEd4MFhPSXUva2NX
SDlSQnVQWERrTnkzSXlObU82QWF0bW5SejF3NDdOcnl2cXdNNzFKQWFrCkpKMCt3
MzhQOFF2SUxQN3ZQbzJvdUx0TGZwcWlnbW5xSWRmcHZKU0VBRG1YWVNrYXJLWHRO
WkxlaElLRnNKR08KcHEwMi9VMjRrOVFlUTBMR1craHpwM2Z2Zk8rcmtQcEFUMlNu
blJycnhSV21mcWRxNUNvZlAyQit0MTkxSGhOVgp6Lzc3SlVJVUZQUGhLQmk5U2xT
cVZDUGlPQmx3VExuWkxpbkJDb3J6S2g4am1LYzB5QUpjQkRnUS9Fd2tjaDNuCi9I
R0t0WW1zZFRDS1c2RUxVcFdGalhkVTIvNEtZME5nbE9MOGxzM0ltWGdKYWdySHli
TmFKZ1VGSkM4bUhjVSsKSy85Q2YxNFZGTGJxaEx0STgvMjlQSlU3TjFacVRpR3lK
ZHBJK1ZCalRDOWptaXpQNUFmRmMvakV5djdkVVg2TAoyeTlldlpnTE1Fb3lrM3lh
VXoyWkFQdFplaW5CR05neFBWc3o4L0ZHaTIzeUpBUmJIcFRqNDlITkNOY295WGdu
Ckxhb1VyQVFrNEpBaFBQYUxQNFZ0UVpoSnRKNno1aGNNQkdlVnBqZGdrT1ZtYWFn
OVZacHNOaGdsN0xIMktXVWQKS0FZTEJtdHMvZEFRbFRQWVQvWDdBb0lCQVFESFZW
YlE3RVJNbUxRaXdicVF2c0hnTUg0bExVbnAvM1ZRMVZ2UQpQc1dPLzJZR3dzTy94
dkxWRldmL3FSbjd4TjZXUFRoZTJFMElPZ1ZEcnZSa1ptTGkwOUZXcTFoNVR6VTV4
T0R0CkhkNDg1aVNQeE1mYTJxdm5hcDF1S0Nsd3N3TjlGSXdOVmNZVGNXU1N2bStB
VmdZMU1pSW81SFkzTEN4Q2N2a0QKdlFXWlJKRWlzQWllc0xGeWh4Z3pHVEVObDdB
VmhqSHF3dGhCNjBXUzdxeW85OUFoV2tKYmZsMVZiMmdyMUsvdApla1dER2JuTTYx
R2FlN1FsVjh5ZWxFRWRNbFVGZUpGcXNnUnAzdTZTQ2lZdThRRzFOM2VQalkvTVZ6
TndvV0JGCnM1Q2hvWGkzeDdTY3RnRnl3ZXJYRDdQeVRPMWNSYkZYYnhOeHFUbVE4
MEFKbytqREFvSUJBUUM5ZjFYVjF1MzIKQkpyOGxXR05zNHEwRmE2bVhpb1FXRnFN
Z3g2bmdIdnpRc2VEV0UxalZwZHJOYjQyWjFpTjJFeGNCZUoyRktiZgp5SDV0SUpT
dVNjRDcvc3hHdW8rNTlMVXRRQ2ZpSFZCZ0NWaUlJcU5yVWJJOFBHYU4vYnNBUTJu
ODZnZlNOSnl3CjFsVFNnNGx1WW1zZUszUXBuWDJZcW5TcGlHdnNTbWwvejBIeU9C
N2NFcklmWWtYNGVRRS94QXg5VmFvTVhNOFEKNkk5NFYrd0NzeGtKUkZPOTJ1Z09C
SmpoZDVxRmVzcTlWdXAxSjAwWkpLbjgxbUFOL2dwS1pUcW45K3gwR3UySgpGRklk
c0tGWVNaQ0NOK0RZR2VvTzhXUlpyQVVGaUVWMFo0d0N4YThKTWhkNXlxd3BIRHdu
bHN2ZEpSbytXSm02CmdUUlg3c3J6NTZBTEFvSUJBRndCcmdMZEsyRlhrcjRBUWNj
UjVaYy9pdHBLSHpYYzdoK1RlNytSV2NyNVkvUjIKN2JlVmN2eWIxdGNSREtkRFph
SmZPNmU3bTBMUzFSODZvQisvaXFFOE9BSVRNTkU5bUVuRDhEWkNkUlFTL29sRgp3
U0hwa1ROTjZNQ3gxUDdxQWhBMzdiVXlCQzF4UjRUY1ZjY2M3ZHliK1Z4NnAzNHI2
M240YTZ3b0VXOS9VS1o4CkxsNWhIR2JLcUliZGQrRFlSVFNLTG53MzEyNEYxS1ZQ
ZVc2OGc5c0JPR1BXM2VuVGRIZld3aVdSTElpbzFUUWEKNGgyMlA1NkUrak93SnFY
OVYzVWhBNjRGNFRlazZPV0x2YmdwRWlxOUlYaW5WTnB5M1pGOVMxeWcxMzlqY3I4
UgpkUEpvcUI1NkY1V1E3L1JGUWNJM2dQWGtsVXIvVzB6bW1vWlltOVVDZ2dFQWQ3
S1lVSlFNQ2V2TXpxRzVWbDNECnpvOG5tL1U5RXNnTW9sY3NwTmVXOUFrSnA2Qytl
WEk0QVVPWVhCc1pwN2VxUERLSFl0a1dzNktjb1dnRUlyZDUKekhPZEswd3EvMlpn
ankzSVE1OEtweThnR2hYdkxob1R3TkxTWVB5V0E4dVJobTE1OVVEQWZUOVZvd2Z0
WnFtSwpTaXRlbSs3Y1ovTzc3MTY1OVM3bnh4RHU4Z2FiRDU1TG4yRmZHMTJyK1ZC
b0p6OVdRNnJZTFRFSmR4WHFnYVlKCnVYM01lODlyNTNibDd2Mnl3SC9ZMHBLMVZM
MDNpUnRNdU9YZEZObVVQSHdHK2hTejZuOGI3Z3ZFOXZZY1pIMUwKWjhYT0pCTHlj
dS90MkdxOVhVby92UkN2TXcwVnpIUTB1ZnpZbExzK0VDL0RwSFFNU0xlRW0zZUR6
Y3VMclZkeApFd0tDQVFCd0ZzZlFXaUEyN3NkWE9HUnhRcVU1NmIvTUl5SVJQcklD
cFdTSVlVekx5Q0pWZ1dVSnNpeitvYlNNCjRkRjJnd2RacGdXejZJaldMQmF6Y0RI
WEplYUptREx4N0Z6V2VsdWRxR1hNZzdJaHoyM1lsZFl3eDJTYUNUUTQKNFcyUnpR
Qlh4UTlnMDB6UmRKa2huMUpyODAvWXcrQVRGN0Q1UkxNYnNxc05lR01iYlVtNDcr
ZjVhMXAwU1NSVQplOXZxZnQrSHgwdTh3SzdYM3RXMjBaaG5mR2U2aGJMRGZFN2l5
ZlZYd013WW1GYkJFNzZwdnVqamhNOG9VSmtmCnFGVVdVVDVzYmFNM1lqR2dSZzY5
cE5xbVVUTTF0TkhRQTI0WlREYkYyUkVGUzBiQWI2VzVzcVdqb2hiL2lPZmEKQ2Fp
VEVlU3RCNnpjVVVUNXV3c2s3bFhia2RiUwotLS0tLUVORCBQUklWQVRFIEtFWS0t
LS0tCg==
-----END PRIVATE KEY-----`;

    const options = {
      client_id: "1",
      username: "username",
      privateKey,
      validate: async function (result) {
        return !!result.access_token;
      },
      onclose: function () {
        console.log("Widget closed");
      },
    };

    // initialize bot only after external script loads
    const interval = setInterval(() => {
      if (window.PZRobot) {
        const bot = new window.PZRobot(options);
        bot.open();
        clearInterval(interval);
      }
    }, 100);

    return () => clearInterval(interval);
  }, []);

  return (
    <>
      <Script
        src="https://d3ciu0yrrqiblg.cloudfront.net/ira_cdn/ira_agent.js"
        strategy="afterInteractive"
      />  
    </>

  );
}
